### ISSUE TITLE
PostgreSQL compatibility

### ISSUE THREAD

**Issue by Rjevski** [sipsorcery-org/signalrtc#2]
Hello and I hope you are well!

I'd like some advice with regards to making this project run with PostgreSQL.

I've installed the `Npgsql.EntityFrameworkCore.PostgreSQL` package (as well as associated ones like `.Design`) and changed all occurrences of `.UseSqlite` with `UseNpgsql` as well as the connection strings. That works fine and it's able to connect to the DB.

The problem is that trying to make and run the migrations fails as it's trying to create some columns as `nvarchar` which aren't supported in Postgres. Those are defined in the `SIPAssetsDbContext.cs`'s `OnModelCreating`.

Are those table creation definitions the canonical representations of the entities and I should edit them to give them the proper columns, or are they autogenerated based on other classes and I should somehow regenerate it (with the new Postgres backend configured)? For example in other web frameworks such as Django you'd define your model classes in code and the actual DB-specific SQL is dynamically derived from those at the time you run the migrations based on the currently configured DB backend (of course this will fail if you explicitly use DB-specific fields, but for common types such as strings or timestamps it would automatically do the right thing and translate to whatever DB backend you're using).

If I try `dotnet ef dbcontext scaffold` it will generate an empty `SIPAssetsDbContext` with no models.

Regards.

**Comment by sipsorcery** [comment]
This is not a very polished app. It was originally a quick and dirty prototype that I ended up finding useful but then never got around to adding fundamental usability docs.

As far as data modelling goes I wrote the DB schema and generated the models from that using the steps outlined in [README.EFCore.txt](https://github.com/sipsorcery-org/signalrtc/blob/master/docs/README.EFCore.txt). The MSSQL schema is [here](https://github.com/sipsorcery-org/signalrtc/blob/master/docs/sipassets_schema_mssql.sql).

I expect it wouldn't take much to tweak that schema for Postgres so that run the `ef dbcontext scaffold` command generates a usable data layer. In this case I'd recommend database first for EF Core as I have not set the project up for code first.

**Comment by Rjevski** [comment]
Thanks for the quick reply!

Yes no worries about the docs! So you're saying that the schema is defined manually as SQL and models are generated from there, got it! This makes sense and I can do the same with Postgres. I was just wondering if I was being an idiot and missing something obvious.

In my case the data model would ideally be managed by my existing Django project, so DB-first would work fine there.
